version: '1.0'

services:
  ecommerce_db:
    image: postgres:alpine3.17
    container_name: ecommerce_db
    environment:
      - POSTGRES_USER=sense
      - POSTGRES_DB=sense_db
      - POSTGRES_PASSWORD=sense_123
    ports:
      - "5434:5432"
    volumes:
      - ecommerce_db:/var/lib/postgresql/data
volumes:
  ecommerce_db:
    driver: local
    